version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build



# Define the jobs we want to run for this project looooool
jobs:
  build:
    working_directory: ~/NotesSaverApp 
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@8.1.4'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install       
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf SaveNotesApp/; git clone https://github.com/Fawas32/NotesSaverApp; source SaveNotesApp/deploy.sh"